export const actionRecipes = {
  primary: "inline-flex items-center justify-center gap-2 rounded-xl bg-[var(--color-action-primary)] px-4 py-2 text-sm font-medium text-[var(--color-text-on-accent)] transition hover:bg-[var(--color-action-primary-hover)] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[var(--color-focus-soft)] disabled:cursor-not-allowed disabled:opacity-60",
  primaryLarge: "inline-flex w-fit shrink-0 items-center justify-center gap-2 rounded-2xl bg-[var(--color-action-primary)] px-5 py-3 text-sm font-medium text-[var(--color-text-on-accent)] shadow-[var(--ds-shadow-surface)] transition hover:bg-[var(--color-action-primary-hover)] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[var(--color-focus-soft)] disabled:cursor-not-allowed disabled:opacity-60",
  secondary: "inline-flex items-center justify-center gap-2 rounded-xl border border-[var(--color-border-subtle)] bg-[var(--color-surface-primary)] px-4 py-2 text-sm font-medium text-[var(--color-selection-strong)] shadow-[var(--ds-shadow-surface)] transition hover:border-[var(--color-border-default)] hover:bg-[var(--color-selection)] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[var(--color-focus-soft)] disabled:cursor-not-allowed disabled:opacity-60",
  secondaryLarge: "inline-flex w-fit shrink-0 items-center justify-center gap-2 rounded-2xl border border-[var(--color-border-subtle)] bg-[var(--color-surface-primary)] px-5 py-3 text-sm font-medium text-[var(--color-selection-strong)] shadow-[var(--ds-shadow-surface)] transition hover:border-[var(--color-border-default)] hover:bg-[var(--color-selection)] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[var(--color-focus-soft)] disabled:cursor-not-allowed disabled:opacity-60",
  tertiaryPill: "inline-flex shrink-0 items-center gap-1.5 whitespace-nowrap rounded-full border border-[var(--color-border-subtle)] bg-[var(--color-surface-primary)] px-3 py-1.5 text-xs font-medium text-[var(--color-selection-strong)] shadow-[var(--ds-shadow-surface)] transition hover:border-[var(--color-border-default)] hover:bg-[var(--color-selection)] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[var(--color-focus-soft)]",
  quickActionPrimary: "group flex min-h-20 w-full flex-col items-center justify-center gap-2 rounded-2xl border border-transparent bg-[var(--color-action-primary)] p-3 text-center text-xs font-medium leading-tight text-[var(--color-text-on-accent)] shadow-[var(--ds-shadow-surface)] transition hover:bg-[var(--color-action-primary-hover)] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[var(--color-focus-soft)]",
  quickActionSecondary: "group flex min-h-20 w-full flex-col items-center justify-center gap-2 rounded-2xl border border-[var(--color-border-subtle)] bg-[var(--color-surface-primary)] p-3 text-center text-xs font-medium leading-tight text-[var(--color-selection-strong)] shadow-[var(--ds-shadow-surface)] transition hover:border-[var(--color-border-default)] hover:bg-[var(--color-selection)] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[var(--color-focus-soft)]",
  quickActionIconPrimary: "flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-[var(--color-text-on-accent)]/15 text-[var(--color-text-on-accent)]",
  quickActionIconSecondary: "flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-[var(--color-selection)] text-[var(--color-selection-strong)]",
  entityDetailIcon: "inline-flex h-9 w-9 shrink-0 items-center justify-center rounded-xl border border-[var(--color-border-subtle)] bg-[var(--color-surface-primary)] text-[var(--color-selection-strong)] shadow-[var(--ds-shadow-surface)] transition hover:border-[var(--color-border-default)] hover:bg-[var(--color-selection)] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[var(--color-focus-soft)]",
  destructive: "inline-flex items-center justify-center gap-2 rounded-xl bg-[var(--color-danger)] px-4 py-2 text-sm font-medium text-white transition hover:opacity-90 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[var(--color-danger-soft)] disabled:cursor-not-allowed disabled:opacity-60",
} as const;
