export const dataDisplayRecipes = {
  metric: "rounded-2xl border border-[var(--color-border-subtle)] bg-[var(--color-surface-primary)]/85 p-4 shadow-[var(--ds-shadow-surface)]",
  metricCompact: "rounded-2xl border border-[var(--color-border-subtle)] bg-[var(--color-surface-primary)]/85 p-3 shadow-[var(--ds-shadow-surface)]",
  metricCompactLabel: "flex items-center gap-2 text-xs font-[var(--font-weight-label)] uppercase tracking-wide text-[var(--color-text-secondary)]",
  metricCompactValue: "mt-1 text-xl font-[var(--font-weight-data)] leading-tight tracking-tight text-[var(--color-text-primary)] tabular-nums",
  metricCompactValueRelevant: "font-[var(--font-weight-data-emphasis)]",
  metricCompactValueEmphasis: "font-[var(--font-weight-heading)]",
  metricCompactHelper: "mt-1 text-xs font-[var(--font-weight-body)] text-[var(--color-text-secondary)]",
  metricLabel: "flex items-center gap-2 text-xs font-[var(--font-weight-heading)] uppercase tracking-wide text-[var(--color-text-secondary)]",
  metricValue: "mt-2 text-2xl font-[var(--font-weight-heading)] tracking-tight text-[var(--color-text-primary)] tabular-nums",
  metricHelper: "mt-1 text-xs text-[var(--color-text-secondary)]",
  operationalRow: "cursor-pointer transition hover:bg-[var(--color-selection)]/50",
  compactRow: "cursor-pointer p-3 transition hover:bg-[var(--color-selection)]/50 sm:p-4",
  compactDatum: "rounded-2xl border border-[var(--color-border-subtle)] bg-[var(--color-surface-primary)]/80 px-3 py-2",
  compactDatumLabel: "text-[10px] font-[var(--font-weight-label)] uppercase tracking-wide text-[var(--color-text-muted)]",
  compactDatumValue: "mt-1 truncate font-[var(--font-weight-data-emphasis)] text-[var(--color-text-primary)] tabular-nums",
  flatDatumLabel: "text-[10px] font-[var(--font-weight-label)] uppercase tracking-wide text-[var(--color-text-muted)]",
  flatDatumValue: "mt-0.5 truncate text-xs font-[var(--font-weight-data-emphasis)] text-[var(--color-text-primary)] tabular-nums",
  entityLink: "font-[var(--font-weight-data-emphasis)] text-[var(--color-selection-strong)] hover:underline",
  compactEntityLink: "block truncate font-[var(--font-weight-data-emphasis)] text-[var(--color-selection-strong)] hover:underline",
  entityAvatar: "mt-0.5 flex h-9 w-9 shrink-0 items-center justify-center rounded-2xl bg-[var(--color-selection)] text-[var(--color-selection-strong)]",
  tableHead: "whitespace-nowrap px-5 py-3 text-left font-[var(--font-weight-heading)]",
  tableCell: "whitespace-nowrap px-5 py-3.5 font-[var(--font-weight-data)] text-[var(--color-text-secondary)]",
  numericCell: "font-[var(--font-weight-data-emphasis)] text-[var(--color-text-primary)] tabular-nums",
  suggestionTitle: "truncate text-sm font-[var(--font-weight-data-emphasis)] text-[var(--color-text-primary)]",
  sectionTitle: "text-xl font-[var(--font-weight-heading)] tracking-tight text-[var(--color-text-primary)]",
  supportingWarning: "text-xs font-[var(--font-weight-label)] text-[var(--color-warning)]",
  emptyState: "flex flex-col items-center justify-center text-center text-[var(--color-text-secondary)]",
} as const;
