export const formRecipes = {
  label: "mb-1.5 block text-sm font-medium text-[var(--color-text-secondary)]",
  labelWithIcon: "mb-1.5 flex items-center gap-2 text-sm font-medium text-[var(--color-text-secondary)]",
  control: "w-full rounded-2xl border border-[var(--color-border-subtle)] bg-[var(--color-surface-subtle)] px-4 py-2.5 text-sm text-[var(--color-text-primary)] outline-none transition placeholder:text-[var(--color-text-muted)] focus:border-[var(--color-focus)] focus:bg-[var(--color-surface-primary)] focus:ring-2 focus:ring-[var(--color-focus-soft)] disabled:cursor-not-allowed disabled:opacity-60",
  searchControl: "w-full rounded-2xl border border-[var(--color-border-subtle)] bg-[var(--color-surface-subtle)] py-2.5 pl-11 pr-10 text-sm text-[var(--color-text-primary)] outline-none transition placeholder:text-[var(--color-text-muted)] focus:border-[var(--color-focus)] focus:bg-[var(--color-surface-primary)] focus:ring-2 focus:ring-[var(--color-focus-soft)]",
  comboboxPanel: "absolute z-40 mt-2 max-h-96 w-full overflow-y-auto rounded-2xl border border-[var(--color-border-default)] bg-[var(--color-surface-elevated)] shadow-[var(--ds-shadow-overlay)]",
  comboboxOption: "w-full px-4 py-3 text-left transition hover:bg-[var(--color-selection)] focus:bg-[var(--color-selection)] focus:outline-none",
  comboboxOptionActive: "bg-[var(--color-selection)]",
  error: "text-xs font-medium text-[var(--color-danger)]",
  help: "text-xs text-[var(--color-text-secondary)]",
  filterOption: "font-[var(--font-weight-body)]",
  filterSelectAll: "font-[var(--font-weight-label)]",
  filterAction: "font-[var(--font-weight-action)]",
  filterSummary: "font-[var(--font-weight-label)]",
} as const;
